services:
  gazebo_nav2:
    build:
      context: .
      network: host
      args:
        https_proxy: http://127.0.0.1:18178
        http_proxy: http://127.0.0.1:18178
        all_proxy: socks5://127.0.0.1:18179
    container_name: gazebo_nav2
    shm_size: 12000m
    ports:
      - "6901:6901" # KasmVNC Web UI端口
    environment:
      - DISPLAY=:1
      - VNC_PW=123456
    volumes:
      - rosbag2_data:/root/rosbag2
    network_mode: host
    tty: true
    stdin_open: true
    command: ["/bin/bash"]

volumes:
  rosbag2_data:
