x-build-args: &build-args
  https_proxy: http://127.0.0.1:18178
  http_proxy: http://127.0.0.1:18178
  all_proxy: socks5://127.0.0.1:18179

services:
  dev:
    image: coscene/gazebo:humble
    build:
      context: .
      dockerfile: docker/Dockerfile
      network: host
      args: *build-args
    tty: true
    stdin_open: true
    command: ["/bin/bash"]
    profiles:
      - dev

  nav_test:
    build:
      context: .
      dockerfile: docker/Dockerfile
      network: host
      args: *build-args
    ports:
      - 21274:21274
    environment:
      - TURTLEBOT3_MODEL=waffle_pi
    command: >
      ros2 launch nav_test test_nav.launch.py --debug
    volumes:
      - ./output:/output
      - ./records/case1:/input
    networks:
      - rosnet

networks:
  rosnet:
