x-build-args: &build-args
  https_proxy: http://127.0.0.1:18178
  http_proxy: http://127.0.0.1:18178
  all_proxy: socks5://127.0.0.1:18179

services:
  nav_test:
    image: coscene/nav_test:humble
    build:
      context: .
      dockerfile: docker/Dockerfile
      network: host
      target: turtlebot3
      args: *build-args
    ports:
      - 21274:21274
    environment:
      - ROS_DISTRO=humble
      - TURTLEBOT3_MODEL=waffle_pi
    command: >
      bash -c 'source /opt/ros/$${ROS_DISTRO}/setup.bash && colcon build && ros2 launch nav_test test_nav.launch.py'
    volumes:
      - ./ros2_ws:/action/ros2_ws
      - ./records/case1:/input
      - ./output:/output
    develop:
      watch:
        - action: sync+restart
          path: ./ros2_ws/src/
          target: /action/ros2_ws/src/
