services:
  nav_test:
    image: ghcr.io/coscene-io/ros:humble-turtlebot3
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: turtlebot3
    ports:
      - 21274:21274
    environment:
      - ROS_DISTRO=humble
      - TURTLEBOT3_MODEL=waffle_pi
    command: >
      bash -c '
        source /opt/ros/$${ROS_DISTRO}/setup.bash &&
        colcon build &&
        source /action/ros2_ws/install/setup.bash &&
        ros2 launch nav_test test_nav.launch.py
      '
    volumes:
      - ros2_ws:/action/ros2_ws
      - .:/action/ros2_ws/src
      - ./records/case1:/input
      - ./output:/output

volumes:
  ros2_ws:
    driver: local
