services:
  nav_test:
    image: ghcr.io/coscene-io/ros:humble-turtlebot3
    build:
      context: .
    ports:
      - "21274:21274" #  Bridge 
      - "8000:8000" #  HTTP serve for the costudio gett the gazebo display file
    environment:
      - ROS_DISTRO=humble
      - TURTLEBOT3_MODEL=waffle_pi
    command: >
      bash -c '
        colcon build &&
        tar czf /cos/bundles/install.tar.gz -C ./install . &&
        /scripts/run.sh
      '
    volumes:
      - gazebo-testing:/action/ros2_ws
      - .:/action/ros2_ws/src
      - ./coscene/records/case1:/cos/files
      - ./output/bundles:/cos/bundles
      - ./output/records:/cos/outputs
      - ./output/reports:/cos/artifacts

volumes:
  gazebo-testing:
    name: gazebo-testing
    driver: local
