services:
  nav_test:
    image: coscene/nav_test:humble
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: turtlebot3
    ports:
      - "21274:21274"
      - "8000:8000"
    environment:
      - ROS_DISTRO=humble
      - TURTLEBOT3_MODEL=waffle_pi
    volumes:
      - ./ros2_ws:/action/ros2_ws
      - ./records/case1:/input
      - ./output:/output
    stop_grace_period: 20s
