points:
  - {'x':  2.1,  'y':  1.5,   'w': 1.0}  # 点1
  - {'x': -0.8,  'y': -1.7,   'w': 1.0}  # 点2
  - {'x': -3.8,  'y':  3.6,   'w': 1.0}  # 点3
  - {'x': -3.2,  'y':  6.8,   'w': 1.0}  # 点4
  - {'x':  0.9,  'y': -3.4,   'w': 1.0}  # 点5
  - {'x': -1.4,  'y':  2.7,   'w': 1.0}  # 点6
  - {'x': -5.8,  'y':  2.3,   'w': 1.0}  # 点7
  - {'x':  3.0,  'y':  2.0,   'w': 1.0}  # 点8
  - {'x': -3.45, 'y':  7.9,   'w': 1.0}  # 点9
  - {'x': -1.09, 'y':  1.45,  'w': 1.0}  # 点10
  - {'x':  3.7,  'y':  2.98,  'w': 1.0}  # 点11
  - {'x': -6.3,  'y':  4.4,   'w': 1.0}  # 点12
  - {'x':  0.8,  'y':  4.72,  'w': 1.0}  # 点13
  - {'x': -0.3,  'y': -1.84,  'w': 1.0}  # 点14
  - {'x': -4.7,  'y':  5.85,  'w': 1.0}  # 点15
  - {'x': -1.55, 'y':  6.28,  'w': 1.0}  # 点16
  - {'x':  2.5,  'y': -0.839, 'w': 1.0}  # 点17
  - {'x':  1.13, 'y':  0.19,  'w': 1.0}  # 点18
  - {'x': -3.73, 'y':  3.7,   'w': 1.0}  # 点19
  - {'x':  1.92, 'y':  3.79,  'w': 1.0}  # 点20

initial_pose: {
  header:  {
    frame_id: "map",
  },
  pose: {
    pose: {
      position: {x: 0.00392, y: -0.0045, z: 0.191},
      orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0},
    },
    covariance: [
      0.25, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.25, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0
    ]
  }
}