#Here is a sample config.yaml file for the operator to run a test suite on coScene's platform.
# Here is the documentation for the config.yaml file: https://docs.coscene.io/docs/sim-and-tests/regression/config-management

# Example file

# Version number, currently supported version is "1"
version: '1'

# Test name is workflow name
name: 'workflow name'

# A job consists of one or more test suites that can be tested in parallel
jobs:
  # First test suite named "test-1"
  - name: For Navigation2 Test
    # Test type is "generic"
    type: generic

    # Image address
    images:
      # Enter image address according to test type
      # make sure you have upload the image to the registry of coScene
      base: /coscene-hello/position:v1.0.0 

    # Associated records
    records:
      # This test suite's associated record label is "sample", which means every record with the same label will be associated with this test suite
      labels:
        - Navigation_Error

    # Run commands for this test suite 
    parameters:
      script:
        - /scripts/run.sh
    
    expose:
      - name: websocket
        port: 21274
      - name: http
        port: 8000

    # Message notification template for test suite "test-1"
    notifications:
      # Notify to DingTalk group or other platforms. Please follow the instructions in the documentation to set up the webhook.
      - dingTalkBot:
          # DingTalk group webhook address
          url: https://oapi.dingtalk.com/robot/send?access_token=xxxxxx
          # Message template
          template: |
            {
              "msgtype": "markdown",
              "markdown": {
                "title": "Test Report",
                "text": "#### Test Report\n> Test suite name: test-1\n> Test result: {{result}}\n> Test duration: {{duration}} seconds\n> Test logs: [link]({{logUrl}})\n"
              }
            }

# Control when to automatically trigger this test
on:
  # Trigger when uploading test bundle that meets the following conditions
  bundlePush:
    category:
      - Navigation
      
name: Nav_test_humble