name: Build and Upload ROS 2 Package

on:
  workflow_dispatch:

jobs:
  colcon-build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/coscene-io/ros:humble-turtlebot3

    steps:
      - uses: actions/checkout@v4
        # with:
        #   path: src

      - name: Build ROS 2 workspace
        run: |
          bash -c ' 
            source /opt/ros/${ROS_DISTRO}/setup.bash
            colcon build
            tar czf install.tar.gz -C ./install .
          '

      - name: Download cos cli
        run: |
          curl https://coscene-artifacts-production.oss-cn-hangzhou.aliyuncs.com/cos/linux/amd64/latest/cos -o /bin/cos
          chmod +x /bin/cos
          mkdir -p $HOME/.cos
          cat > $HOME/.cos/config.yaml << EOF
          platform:
            endpoint: ${{ vars.COSCENE_ENDPOINT }}
            project: batch-test
            accessToken: OWZkN2I5MTczNGJmN2JkNzFkMWE0ZGFmNjMxOGU4MWUxMjFmZDUzOGZhOTc5NDIzZDhlNGU0YTExMzRiMzgxNw==
          EOF

      - name: Push and Trigger Test
        run: |
          cat $HOME/.cos/config.yaml

          ls -l install.tar.gz coscene/matrix/config.yaml ./install
          /bin/cos test run \
            --config $HOME/.cos/config.yaml \
            --test-config coscene/matrix/config.yaml \
            -b install.tar.gz

