name: Build and Push Multi-Arch Docker Images

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distro: ["humble"]
        target:
          # - base
          - turtlebot3
        include:
          # - ros_distro: "humble"
          #   target: "base"
          - ros_distro: "humble"
            target: "turtlebot3"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Private Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image name with timestamp
        id: image_meta
        run: |
          if [ "${{ matrix.target }}" = "base" ]; then
            echo "image_tag=${{ matrix.ros_distro }}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=${{ matrix.ros_distro }}-${{ matrix.target }}" >> $GITHUB_OUTPUT
          fi
          echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          target: ${{ matrix.target }}
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ steps.image_meta.outputs.image_tag }}
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ steps.image_meta.outputs.image_tag }}-${{ steps.image_meta.outputs.commit_sha }}
